//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bookmark_collection_entry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub description: String,
    pub bookmark_collection_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bookmark_collection::Entity",
        from = "Column::BookmarkCollectionId",
        to = "super::bookmark_collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BookmarkCollection,
}

impl Related<super::bookmark_collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookmarkCollection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
