//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::bookmark_collection::Entity as BookmarkCollection;
pub use super::bookmark_collection_entry::Entity as BookmarkCollectionEntry;
pub use super::user_information::Entity as UserInformation;
