//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vault")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: String,
    pub user_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_information::Entity",
        from = "Column::UserId",
        to = "super::user_information::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserInformation,
    #[sea_orm(has_many = "super::vault_entries::Entity")]
    VaultEntries,
}

impl Related<super::user_information::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserInformation.def()
    }
}

impl Related<super::vault_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VaultEntries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
